# 1 Question

In [ ]:
list1=[0,2,4,6,8]
list1

[0, 2, 4, 6, 8]

In [ ]:
list1.append(10)

In [ ]:
list1

[0, 2, 4, 6, 8, 10]

In [ ]:
list1.extend([12,14])

In [ ]:
list1

[0, 2, 4, 6, 8, 10, 12, 14]

In [ ]:
list1.insert(1,16)

In [ ]:
list1

[0, 16, 2, 4, 6, 8, 10, 12, 14]

In [ ]:
list1.remove(8)

In [ ]:
list1

[0, 16, 2, 4, 6, 10, 12, 14]

In [ ]:
list1.pop(6)

12

In [ ]:
list1

[0, 16, 2, 4, 6, 10, 14]

In [ ]:
list1.index(10)

5

In [ ]:
list1.count(14)

1

In [ ]:
list1.sort()

In [ ]:
list1

[0, 2, 4, 6, 10, 14, 16]

In [ ]:
list1.reverse()

In [ ]:
list1

[16, 14, 10, 6, 4, 2, 0]

In [ ]:
list1.clear()

In [ ]:
list1

[]

# 2 Question

In [1]:
tuple1=("john","bob","alice")

In [ ]:
tuple1[1]="david" #because tuple is unmutable

TypeError: 'tuple' object does not support item assignment

the student name will not change and gives TypeError as 'tuple' object does not support item assignment because tuple is immutable

# 3 Question

In [ ]:
set1={1,2,3,3,4,5,5,5}

In [ ]:
set1

{1, 2, 3, 4, 5}

Returns the list without duplicates because set does not allow duplicates

# 4 Question

In [ ]:
dict1={'name':'Anjali',
       'age':20,
       'city':'Hyderabad'}

In [ ]:
dict1.update({"age":21})   # or dict1['age']=21

In [ ]:
dict1['email']='anjali@gmail.com'

In [ ]:
dict1

{'name': 'Anjali', 'age': 21, 'city': 'Hyderabad', 'email': 'anjali@gmail.com'}

# 5 Question

In [2]:
age=int(input("Enter your Age:"))
if age>=18:
  print("you are eligible to vote.")
else:
  print(f"you are not eligible to vote. After {18 - age} you are eligible to vote" )

Enter your Age:12
you are not eligible to vote. After 6 you are eligible to vote


#6 Question

In [15]:
marks=int(input("Enter the marks:"))
if marks>=90:
  print('A')
elif marks>=75 and marks<=89:
  print('B')
elif marks>=50 and marks<=74:
  print('C')
else:
  print('Fail')

Enter the marks:78
B


# 7 Question

In [ ]:
num=int(input("Enter any number:"))
if num>0:
  if num%2==0:
   print(num,"is positive and even number")
  else:
    print(num,"is a positive number")
else:
  if num==0:
    print(num,"is zero")
  else:
      print(num,'is a negative number')

Enter any number:-19763
-19763 is negative number


# 8 Question

In [19]:
import numpy as np
arr_scalar=np.array(5)
print(arr_scalar)
type(arr_scalar)

5


numpy.ndarray

In [20]:
arr_1d=np.array([1,2,3,4,5])
print(arr_1d)

[1 2 3 4 5]


In [23]:
arr_2d=np.array([[10,20,30],[40,50,60]])
arr_2d

array([[10, 20, 30],
       [40, 50, 60]])

In [25]:
arr_rand=np.random.randint(0,100,size=(4))
arr_rand

array([96, 39, 24,  9])

In [ ]:
arr_rand2=np.random.randint(1,100,size=(3,3))
arr_rand2

array([[43, 16, 23],
       [33, 81, 90],
       [61, 80, 86]])

In [ ]:
import pandas as pd
df1=pd.DataFrame(arr_rand2,columns=("A","B","C"))
df1

A   B   C
0  43  16  23
1  33  81  90
2  61  80  86

# 11 Question

In [ ]:
import numpy as np
people = (
    ("Alice", 21, "Hyderabad", 50000),
    ("Bob", 25, "Delhi", 60000),
    ("Ian", 29, "Lucknow", 72000),
    ("David", 28, "Bangalore", np.nan),
    ("Eva", 22, "Chennai", 52000),
    ("Alice", 21, "Hyderabad", 50000),
    ("Grace", 24, "Kolkata", 58000),
    ("Helen", 26, "Jaipur", np.nan),
    ("Ian", 29, "Lucknow", 72000),
    ("Judy", 30, "Ahmedabad", np.nan)
)

In [ ]:
people

(('Alice', 21, 'Hyderabad', 50000),
 ('Bob', 25, 'Delhi', 60000),
 ('Ian', 29, 'Lucknow', 72000),
 ('David', 28, 'Bangalore', nan),
 ('Eva', 22, 'Chennai', 52000),
 ('Alice', 21, 'Hyderabad', 50000),
 ('Grace', 24, 'Kolkata', 58000),
 ('Helen', 26, 'Jaipur', nan),
 ('Ian', 29, 'Lucknow', 72000),
 ('Judy', 30, 'Ahmedabad', nan))

In [ ]:
df2=pd.DataFrame(people, columns=("Name","Age","City","Salary"))
df2

Name  Age       City   Salary
0  Alice   21  Hyderabad  50000.0
1    Bob   25      Delhi  60000.0
2    Ian   29    Lucknow  72000.0
3  David   28  Bangalore      NaN
4    Eva   22    Chennai  52000.0
5  Alice   21  Hyderabad  50000.0
6  Grace   24    Kolkata  58000.0
7  Helen   26     Jaipur      NaN
8    Ian   29    Lucknow  72000.0
9   Judy   30  Ahmedabad      NaN

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  7 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [ ]:
df2.describe()

Age        Salary
count  10.000000      7.000000
mean   25.500000  59142.857143
std     3.439961   9581.728644
min    21.000000  50000.000000
25%    22.500000  51000.000000
50%    25.500000  58000.000000
75%    28.750000  66000.000000
max    30.000000  72000.000000

In [ ]:
df2[["Name","City"]]

Name       City
0  Alice  Hyderabad
1    Bob      Delhi
2    Ian    Lucknow
3  David  Bangalore
4    Eva    Chennai
5  Alice  Hyderabad
6  Grace    Kolkata
7  Helen     Jaipur
8    Ian    Lucknow
9   Judy  Ahmedabad

In [ ]:
df2['Salary'].fillna(value=int(df2['Salary'].mean()),inplace=True)
df2

/tmp/ipython-input-152954126.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['Salary'].fillna(value=int(df2['Salary'].mean()),inplace=True)


Name  Age       City   Salary
0  Alice   21  Hyderabad  50000.0
1    Bob   25      Delhi  60000.0
2    Ian   29    Lucknow  72000.0
3  David   28  Bangalore  59142.0
4    Eva   22    Chennai  52000.0
5  Alice   21  Hyderabad  50000.0
6  Grace   24    Kolkata  58000.0
7  Helen   26     Jaipur  59142.0
8    Ian   29    Lucknow  72000.0
9   Judy   30  Ahmedabad  59142.0

In [ ]:
df2.drop_duplicates(ignore_index=True, inplace=True)

In [ ]:
df2

Name  Age       City   Salary
0  Alice   21  Hyderabad  50000.0
1    Bob   25      Delhi  60000.0
2    Ian   29    Lucknow  72000.0
3  David   28  Bangalore  59142.0
4    Eva   22    Chennai  52000.0
5  Grace   24    Kolkata  58000.0
6  Helen   26     Jaipur  59142.0
7   Judy   30  Ahmedabad  59142.0